import { boolean, integer, pgTable, real, serial, text, timestamp } from "drizzle-orm/pg-core";

export const inventoryLotsTable = pgTable("inventory_lots", {
  id: serial("id").primaryKey(),
  inventory_item_id: integer("inventory_item_id"),
  product_name: text("product_name").notNull(),
  retailer: text("retailer").notNull().default("Costco"),
  store_location: text("store_location").notNull().default("Unknown"),
  category: text("category"),
  purchase_date: text("purchase_date").notNull(),
  quantity_bought: integer("quantity_bought").notNull().default(1),
  quantity_sold: integer("quantity_sold").notNull().default(0),
  quantity_remaining: integer("quantity_remaining").notNull().default(1),
  unit_purchase_price: real("unit_purchase_price").notNull().default(0),
  sales_tax_total: real("sales_tax_total").notNull().default(0),
  total_purchase_price: real("total_purchase_price").notNull().default(0),
  average_unit_cost: real("average_unit_cost").notNull().default(0),
  listed_price: real("listed_price"),
  expected_sale_price: real("expected_sale_price"),
  estimated_profit: real("estimated_profit"),
  receipt_photo_url: text("receipt_photo_url"),
  payment_method: text("payment_method").notNull().default("Cash"),
  status: text("status").notNull().default("Bought"),
  notes: text("notes"),
  is_deleted: boolean("is_deleted").notNull().default(false),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const saleTransactionsTable = pgTable("sale_transactions", {
  id: serial("id").primaryKey(),
  inventory_lot_id: integer("inventory_lot_id").notNull(),
  inventory_item_id: integer("inventory_item_id"),
  sale_date: text("sale_date").notNull(),
  quantity_sold: integer("quantity_sold").notNull().default(1),
  sold_price_per_unit: real("sold_price_per_unit").notNull().default(0),
  total_sold_price: real("total_sold_price").notNull().default(0),
  sale_channel: text("sale_channel").notNull().default("Facebook Marketplace"),
  platform_fee: real("platform_fee").notNull().default(0),
  shipping_charged_to_buyer: real("shipping_charged_to_buyer").notNull().default(0),
  shipping_cost: real("shipping_cost").notNull().default(0),
  packaging_cost: real("packaging_cost").notNull().default(0),
  delivery_gas_cost: real("delivery_gas_cost").notNull().default(0),
  other_expense: real("other_expense").notNull().default(0),
  net_sale_proceeds: real("net_sale_proceeds").notNull().default(0),
  gross_profit: real("gross_profit").notNull().default(0),
  net_profit: real("net_profit").notNull().default(0),
  profit_margin_percent: real("profit_margin_percent").notNull().default(0),
  roi_percent: real("roi_percent").notNull().default(0),
  buyer_payment_method: text("buyer_payment_method").notNull().default("Cash"),
  sale_screenshot_url: text("sale_screenshot_url"),
  buyer_notes: text("buyer_notes"),
  notes: text("notes"),
  is_deleted: boolean("is_deleted").notNull().default(false),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const expenseTransactionsTable = pgTable("expense_transactions", {
  id: serial("id").primaryKey(),
  expense_date: text("expense_date").notNull(),
  expense_type: text("expense_type").notNull().default("Other"),
  amount: real("amount").notNull().default(0),
  related_inventory_item_id: integer("related_inventory_item_id"),
  related_inventory_lot_id: integer("related_inventory_lot_id"),
  related_store: text("related_store"),
  notes: text("notes"),
  receipt_photo_url: text("receipt_photo_url"),
  is_deleted: boolean("is_deleted").notNull().default(false),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const ledgerEntriesTable = pgTable("ledger_entries", {
  id: serial("id").primaryKey(),
  entry_date: text("entry_date").notNull(),
  entry_type: text("entry_type").notNull(),
  inventory_item_id: integer("inventory_item_id"),
  inventory_lot_id: integer("inventory_lot_id"),
  sale_transaction_id: integer("sale_transaction_id"),
  expense_transaction_id: integer("expense_transaction_id"),
  description: text("description").notNull(),
  retailer: text("retailer"),
  store_location: text("store_location"),
  product_name: text("product_name"),
  category: text("category"),
  quantity: integer("quantity").notNull().default(1),
  money_out: real("money_out").notNull().default(0),
  money_in: real("money_in").notNull().default(0),
  net_amount: real("net_amount").notNull().default(0),
  running_cash_position: real("running_cash_position"),
  status: text("status"),
  notes: text("notes"),
  is_deleted: boolean("is_deleted").notNull().default(false),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export type InventoryLot = typeof inventoryLotsTable.$inferSelect;
export type SaleTransaction = typeof saleTransactionsTable.$inferSelect;
export type ExpenseTransaction = typeof expenseTransactionsTable.$inferSelect;
export type LedgerEntry = typeof ledgerEntriesTable.$inferSelect;
