import { boolean, integer, pgTable, real, serial, text, timestamp } from "drizzle-orm/pg-core";

export const thriftScanSessionsTable = pgTable("thrift_scan_sessions", {
  id: serial("id").primaryKey(),
  store_name: text("store_name"),
  store_address: text("store_address"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  gps_latitude: real("gps_latitude"),
  gps_longitude: real("gps_longitude"),
  place_confidence: integer("place_confidence"),
  user_confirmed_location: boolean("user_confirmed_location").notNull().default(false),
  started_at: text("started_at").notNull(),
  ended_at: text("ended_at"),
  total_items_scanned: integer("total_items_scanned").notNull().default(0),
  buy_count: integer("buy_count").notNull().default(0),
  maybe_count: integer("maybe_count").notNull().default(0),
  skip_count: integer("skip_count").notNull().default(0),
  research_more_count: integer("research_more_count").notNull().default(0),
  estimated_total_profit: real("estimated_total_profit").notNull().default(0),
  notes: text("notes"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export const thriftScanItemsTable = pgTable("thrift_scan_items", {
  id: serial("id").primaryKey(),
  thrift_scan_session_id: integer("thrift_scan_session_id"),
  inventory_item_id: integer("inventory_item_id"),
  store_name: text("store_name"),
  store_address: text("store_address"),
  city: text("city"),
  state: text("state"),
  zip: text("zip"),
  gps_latitude: real("gps_latitude"),
  gps_longitude: real("gps_longitude"),
  scan_timestamp: text("scan_timestamp").notNull(),
  timezone: text("timezone"),
  scan_id: text("scan_id").notNull(),
  original_photo_url: text("original_photo_url"),
  stamped_photo_url: text("stamped_photo_url"),
  full_item_photo_url: text("full_item_photo_url"),
  brand_logo_photo_url: text("brand_logo_photo_url"),
  model_number_photo_url: text("model_number_photo_url"),
  price_tag_photo_url: text("price_tag_photo_url"),
  condition_photo_url: text("condition_photo_url"),
  receipt_photo_url: text("receipt_photo_url"),
  asking_price: real("asking_price"),
  negotiated_price: real("negotiated_price"),
  quantity: integer("quantity").notNull().default(1),
  product_name: text("product_name").notNull(),
  brand: text("brand"),
  model_number: text("model_number"),
  serial_number: text("serial_number"),
  category: text("category"),
  subcategory: text("subcategory"),
  condition: text("condition"),
  visible_damage: text("visible_damage"),
  missing_parts: text("missing_parts"),
  included_accessories: text("included_accessories"),
  estimated_retail_type: text("estimated_retail_type"),
  ebay_active_range: text("ebay_active_range"),
  ebay_sold_range: text("ebay_sold_range"),
  expected_facebook_sale_price: real("expected_facebook_sale_price"),
  suggested_list_price: real("suggested_list_price"),
  max_buy_price: real("max_buy_price"),
  estimated_profit: real("estimated_profit"),
  recommendation: text("recommendation").notNull().default("RESEARCH_MORE"),
  suggested_channel: text("suggested_channel"),
  confidence_score: integer("confidence_score").notNull().default(50),
  risk_notes: text("risk_notes"),
  user_notes: text("user_notes"),
  created_at: timestamp("created_at").defaultNow().notNull(),
  updated_at: timestamp("updated_at").defaultNow().notNull(),
});

export type ThriftScanSession = typeof thriftScanSessionsTable.$inferSelect;
export type ThriftScanItem = typeof thriftScanItemsTable.$inferSelect;
